version: '3'
services:
  syft:
    build: ./syft
    # Ejecuta jupyter lab en lugar de jupyter
    command: "start.sh jupyter lab --NotebookApp.token=''"
    volumes:
     - ./notebooks:/home/jovyan/work
    #  - ./data:/home/jovyan/work/data
    ports:
     - "8888:8888"
     - "4040:4040"
     - "4041:4041"
     - "8889:8889"
     - "9099:9099"